<?php
/**
=====================================================
			     -:- Z-Programing -:-
-----------------------------------------------------
 * @PROJECT	: Product Slider Pro [ Magebay.com ]
 * @AUTHOR	: Zuko
 * @FILE	: Collection.php
 * @CREATED	: 8:55 AM , 22/02/2016
 * @DETAIL	: 
-----------------------------------------------------
=====================================================
**/


namespace Magebay\Pslider\Model\ResourceModel\Pslider;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection{

    protected $_idFieldName;

    protected function _construct ()
    {
        parent::_construct (); // TODO: Change the autogenerated stub
        $this->_init('Magebay\Pslider\Model\Pslider', 'Magebay\Pslider\Model\ResourceModel\Pslider');
    }
}