<?php
/**
 * Magebay 
 * @category    Magebay 
 * @copyright   Copyright (c) 2017 Magebay (http://magebay.com/) 
 * @Author: Hanh Nguyen<hanhkaka.nguyen37@gamil.com>
 * @@Create Date: 2017-05-5
 * @@Modify Date: 2017-06-05
 */
/*--------------------*/

/**
 * @var \Magebay\Pslider\Block\IndexBlock $block
 * @var \Magebay\Pslider\Model\Pslider $sliderlist
 * @var \Magebay\Pslider\Model\Pslider $item
 */
use Magento\Framework\App\Action\Action;
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$sliderlist = $block->getList();
$idBlock = uniqid();
$processed = [];

echo "<pre>";
    var_dump($sliderlist->toArray());
echo "</pre>";
?>
<div id="tab-container-<?=$idBlock?>" class="pslider tabslide">
    <ul class='list-tab'>
        <?php
        $prefixStr = '#pslider';
        foreach ($sliderlist as $item)
        {
            $hrefurl = $prefixStr . $item->getId();
            $title = $item->getTitle();
            ?>
            <li class='tab'><a href="<?=$hrefurl?>"><?=$title?></a></li>
            <?php
        }
        ?>

    </ul>
    <?php
    foreach ($sliderlist as $item) {
        $hrefurl = $prefixStr . $item->getId();
        $tabdivid = str_replace('#','',$hrefurl);
        $owldivid = str_replace('#','owl-',$hrefurl);
        ?>
        <div id="<?=$tabdivid?>" class="mst-content-tab">
            <?php
            $dataSlider = $block->getItemByType($item->getCategoryId(),$item->getTypeId());
            //
            // OWL
            //
            if(count($dataSlider)>0){
			foreach ($dataSlider as $_product) {

                $productSets = $block->isElementOfSet($_product->getId());
                if($productSets)
                {
                    if(array_key_exists($productSets[0],$processed))
                    {
                        continue;
                    }
                    $processed[$productSets[0]] = 1;
                    $_product = $block->getProductDetail($productSets[0]);
                }
                echo "<pre>";
                var_dump($_product->toArray());
                echo "</pre>";
            }
			}else{ echo "test"; }
            ?>
        </div>
        <?php
    }
    ?>
</div>
<script type="text/javascript">
    require(["jquery","magebay/easytabs"], function($){
        $('#tab-container-<?=$idBlock?>').easytabs();
    });
</script>
