<?php
/**
=====================================================
			     -:- Z-Programing -:-
-----------------------------------------------------
 * @PROJECT	: Product Slider Pro [ Magebay.com ]
 * @AUTHOR	: Zuko
 * @FILE	: list.phtml
 * @CREATED	: 8:11 AM , 09/03/2016
 * @DETAIL	: 
-----------------------------------------------------
=====================================================
**/
use Magento\Framework\App\Action\Action;
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$sliderlist = $block->getList();
$prefixStr = '#pslider';

foreach ($sliderlist as $item) {
    $processed = [];
    $hrefurl = $prefixStr . $item->getId();
    $tabdivid = str_replace('#','',$hrefurl);
    $owldivid = str_replace('#','owl-',$hrefurl);
    ?>
    <div id="<?=$tabdivid?>">
        <h2><?=$item->getTitle()?></h2>
        <?php
        $dataSlider = $block->getItemByType($item->getCategoryId(),$item->getTypeId());
        //
        // OWL
        //
        ?>
        <div id="<?=$owldivid?>">
            <?php foreach($dataSlider as $_product){
                if($_product->getStatus() == 0 || array_key_exists($_product->getId(),$processed))
                {
                    continue;
                }
                $processed[$_product->getId()] = 1;
                $productSets = $block->isElementOfSet($_product->getId());
                if($productSets)
                {
                    if(array_key_exists($productSets[0],$processed))
                    {
                        continue;
                    }
                    $processed[$productSets[0]] = 1;
                    $_product = $block->getProductDetail($productSets[0]);
                }
                ?>
                <div class="item">
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $block->stripTags($block->getImageLabel($_product, 'small_image'), null, true) ?>"
                       class="product-image" >
                        <?php echo $block->absblock->getImage($_product,'category_page_grid')->toHtml(); ?></a>
                    <div class="product-des">
                        <h2 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $block->stripTags($_product->getName(), null, true) ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h2>
                        <?php if($block->tempSetting->showreviews)	echo( $block->absblock->getReviewsSummaryHtml($_product,'short',true)); ?>
                        <?php /* @escapeNotVerified */
                        if($block->tempSetting->showprice) echo $block->absblock->getProductPrice($_product) ?>
                    </div>
                    <div class="actions">
                        <?php if ( $block->tempSetting->showaddcart )  { ?>
                            <div class="actions-primary">
                                <?php if($_product->isSaleable()): ?>
                                    <?php $postParams = $block->absblock->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php echo $block->absblock->getBlockHtml('formkey')?>
                                        <button type="submit"
                                                title="<?php echo $block->absblock->escapeHtml(__('Add to Cart')); ?>"
                                                class="action tocart primary">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    </form>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo __('Out of stock') ?></span></p>
                                <?php endif; ?>
                            </div>
                            <div data-role="add-to-links" class="actions-secondary">
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                    <a href="#"
                                       class="action towishlist"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->absblock->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                    </a>
                                <?php endif; ?>
                                |
                                <?php
                                /**
                                 * @var Magento\Catalog\Helper\Product\Compare $compareHelper
                                 */
                                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                ?>
                                <a href="#"
                                   class="action tocompare"
                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                   role="button">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                </a>
                            </div>

                        <?php } ?>
                    </div>
                </div>
                <?php
            }?>
        </div>
        <script type="text/javascript">
            require(["jquery","Magebay_Pslider/owl-carousel/owl.carousel.min"], function($){
                $('#<?=$owldivid?>').owlCarousel({
                    autoPlay: <?=$block->_configHelper->getAutoplay()?>,
                    items: <?=$block->_configHelper->getSliderItem()?>,
//			loop : true,
                    pagination: false,
                    navigation: true,
                    stopOnHover: <?=$block->_configHelper->getAutoplay()?>,
                    slideSpeed:  <?=$block->_configHelper->getSliderSpeed()?>,
                    itemsDesktop: [1199, 3],
//			itemsCustom: [[0, 2], [400, 3], [700, 4], [1000, 5], [1200, 6], [1600, 8]],
                    itemsDesktopSmall: [979, 3]
                });
            });
        </script>
    </div>
    <?php
}
