<?php
/**
 * Magebay 
 * @category    Magebay 
 * @copyright   Copyright (c) 2017 Magebay (http://magebay.com/) 
 * @Author: Hanh Nguyen<hanhkaka.nguyen37@gamil.com>
 * @@Create Date: 2017-05-5
 * @@Modify Date: 2017-06-05
 */
/*--------------------*/

use Magento\Framework\App\Action\Action;
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<div id="pslider<?php echo $block->getTabId(); ?>" class="mst-content-tab products-grid">
	<?php $dataSlider = $block->getItemByType($block->getCatId(),$block->getType()); ?>
	<?php if(count($dataSlider)>0){ ?>
		<div id="owl-pslider<?php echo $block->getTabId(); ?>" class="owl-carousel">
			<?php foreach($dataSlider as $_product){ ?>
				<div class="item">
					<div class="product-top">
							<a href="<?php echo $_product->getProductUrl() ?>"
							   title="<?php echo $block->stripTags($block->getImageLabel($_product, 'small_image'), null, true) ?>"
							   class="product-image" >
								<?php echo $block->getImage($_product,'category_page_grid')->toHtml(); ?></a>							
							<div data-role="add-to-links" class="actions-secondary">
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
									<a href="#"
										class="action towishlist"
										title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
										data-action="add-to-wishlist"
										role="button">
										<i class="fa fa-heart-o"></i>
									</a>
								<?php endif; ?>
								<?php
									/**
									 * @var Magento\Catalog\Helper\Product\Compare $compareHelper
									 */
									$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
								?>
								<a href="#"
									class="action tocompare"
									title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
									data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
									role="button">
									<i class="fa fa-bar-chart"></i>
								</a>
							</div>
						</div>
						<div class="product-des">
                            <h2 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $block->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </h2>
                            <?php if($block->tempSetting->showreviews)	echo $block->getReviewsSummaryHtml($_product,'short',true); ?>
                            <?php /* @escapeNotVerified */
                            if($block->tempSetting->showprice) echo $block->getProductPrice($_product); ?>
							<?php if($block->tempSetting->showaddcart){ ?>
								<div class="actions-primary">
									<?php if($_product->isSaleable()): ?>
										<?php $postParams = $block->getAddToCartPostParams($_product); ?>
										<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
											<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
											<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
											<?php echo $block->getBlockHtml('formkey')?>
											<button type="submit"
													title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
													class="action tocart primary">
												<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
											</button>
										</form>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo __('Out of stock') ?></span></p>
									<?php endif; ?>
								</div>
							<?php } ?>
                        </div>
				</div>
			<?php } ?>
		</div>
		<script type="text/javascript">
                require(["jquery","magebay/owlcarousel"], function($){
                    $('#owl-pslider<?php echo $block->getTabId(); ?>').owlCarousel({
                        autoplay: <?=$block->_configHelper->getAutoplay()?>,
                        autoplayTimeout: <?=$block->_configHelper->getAutotimeout()?>,
						stopOnHover: <?=$block->_configHelper->getAutoplay()?>,
						slideSpeed:  <?=$block->_configHelper->getSliderSpeed()?>,						
						//loop:true,
						responsiveClass:true,
						responsive:{
							0:{
								margin:10,
								items:1
								
							},
							375:{
								margin:10,
								items:2
							},
							600:{
								margin:10,
								items:3
							},
							768:{
								margin:10,
								items:2
							},
							992:{
								margin:10,
								items:3
							},
							1200:{
								margin:20,
								items:<?=$block->_configHelper->getSliderItem()-1; ?>
							}
						}
                    });
                });
        </script>
	<?php }else { echo __('We can\'t find products matching the selection.'); } ?>
</div>